apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
        env: development
    spec:
      containers:
      - name: my-app
        image: gcr.io/b00919848-cloud/app:latest
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
  selector:
    app: my-app