apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
        env: development
    spec:
      containers:
      - name: my-app1
        image: gcr.io/b00919848-cloud/github.com/wrh1997/a3t2@sha256:8bef6c75d62641e3098097c710ffc6a83d7405bb07c699234358977cb8885a60
        ports:
        - containerPort: 6000
        volumeMounts: 
        - mountPath: "./waleed_PV_dir/"
          name: pvc-vol
      - name: my-app2
        image: gcr.io/b00919848-cloud/github.com/wrh1997/a3t3@sha256:3ecf982a4bf100331ad74bad83f85ff5389c13f15ae56800c92b964dd588dc96
        ports:
        - containerPort: 5000
      volumes:
      - name: pvc-vol
        persistentVolumeClaim:
          claimName: pvc-demo
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - name: port6000
    port: 6000
    targetPort: 6000
    protocol: TCP
  - name: port5000
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: my-app