apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
        env: development
    spec:
      containers:
      - name: my-app1
        image: gcr.io/b00919848-cloud/github.com/wrh1997/a3t2@sha256:a09ab036c46ebb38f5f4d8047b7a263ee27b72fc73edf54c3a86afc4219bd125
        ports:
        - containerPort: 6000
        volumeMounts: 
        - mountPath: "/waleed_PV_dir/"
          name: pvc-vol
      - name: my-app2
        image: gcr.io/b00919848-cloud/github.com/wrh1997/a3t3@sha256:166c099227569e60e18a5435addab566dcc302e1edd259fe7abc726e311da114
        ports:
        - containerPort: 5000
        volumeMounts: 
        - mountPath: "/waleed_PV_dir/"
          name: pvc-vol
      volumes:
      - name: pvc-vol
        persistentVolumeClaim:
          claimName: pvc-demo
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - name: port6000
    port: 6000
    targetPort: 6000
    protocol: TCP
  - name: port5000
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: my-app