apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
        env: development
    spec:
      containers:
      - name: my-app1
        image: gcr.io/b00919848-cloud/github.com/wrh1997/a3t2@sha256:3af6d63e8e9c5761ff8093e42abfa18ccc2a2506b90db5919758ea581ac46c96
        ports:
        - containerPort: 6000
        volumeMounts: 
        - mountPath: "/waleed_PV_dir/"
          name: pvc-vol
      - name: my-app2
        image: gcr.io/b00919848-cloud/github.com/wrh1997/a3t3@sha256:821627d44c3ede7c264b81fe3d2f22b33558c35378d4cad2aae3ca79ee157b4c
        ports:
        - containerPort: 5000
        volumeMounts: 
        - mountPath: "/waleed_PV_dir/"
          name: pvc-vol
      volumes:
      - name: pvc-vol
        persistentVolumeClaim:
          claimName: pvc-demo
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - name: port6000
    port: 6000
    targetPort: 6000
    protocol: TCP
  - name: port5000
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: my-app